### ISSUE TITLE
Easier installation instructions

### ISSUE THREAD

**Issue by kachkaev** [devhelp/piwik-bundle#1]
Hi guys! Thanks a lot for the bundle – hope it will really help!

Could you please clarify the instructions a bit for the new users please? Here are the things I struggled with:
1. The ‘Install’ section in README.md normally tells what row to copy to `AppKernel.php`. It took me a couple of minutes to figure out that this is `new Devhelp\PiwikBundle\DevhelpPiwikBundle()` for your bundle. See https://github.com/kachkaev/KachkaevAssetsVersionBundle for an example of what I mean.
2. `my_piwik.client` part is a bit confusing – things don't work out of the box and require you to switch on the brain :–) I ended up with this in `services.yml`:

``` yml
services:
    my_piwik.client:
        class: Devhelp\Piwik\Api\Guzzle\Client\PiwikGuzzleClient
        arguments:
            - "@guzzle"

    guzzle:
        class: Devhelp\Piwik\Api\Guzzle\Client\PiwikGuzzleClient
```

`app/console` works after `composer require  devhelp/piwik-api-guzzle` and a few failed experiments, but I still feel unsure about what I've done.

Thanks again for making the bundle indeed!
